// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:unseen_scout/config/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Env.fbAndroidApiKey,
    appId: '1:613167220460:android:05af0fd575dfc050cdc7c9',
    messagingSenderId: '613167220460',
    projectId: 'unseen-e3b13',
    storageBucket: 'unseen-e3b13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.fbIosApiKey,
    appId: '1:613167220460:ios:642d94fc34eb0c90cdc7c9',
    messagingSenderId: '613167220460',
    projectId: 'unseen-e3b13',
    storageBucket: 'unseen-e3b13.firebasestorage.app',
    androidClientId:
        '613167220460-83eurqic5dvqp6jcd9pt179ug8p8f49b.apps.googleusercontent.com',
    iosClientId:
        '613167220460-fkg7pdgv70t8p6gdlv3fo6ql2jgpolh0.apps.googleusercontent.com',
    iosBundleId: 'com.unseen.scout',
  );
}
